service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

  custom:
    fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

  resources:
    Resources:
      FileBucket:
        Type: AWS::S3::Bucket
        Properties: 
          BucketName: ${self:custom.fileUploadBucketName}
          AccessControl: PublicRead